env: standard
runtime: nodejs12
service: default
instance_class: B1
handlers:
  - url: /.*
    secure: always
    script: auto
  - url: /static
    static_dir: build

basic_scaling:
  max_instances: 4
  idle_timeout: 5m

env_variables:
  NEXT_PUBLIC_STRAPI_API_URL: https://cms-plumademiscreaciones.herokuapp.com